@startuml Diagrama_UML_Autopecas


class Pedido{
    id: Long
    data: LocalDateTime
    valorTotal: Double
    pagamento: Pagamento
    status: StatusPedido
    cupom: Cupom 
}

Pedido --> StatusPedido
Pedido --> Cupom

class Cupom{
    id: Long
    nomeCupom: String
    desconto: Double
}

class ItemPedido{
    id: Long 
    quantidade: Integer
    preco: Double
}

class Pagamento{
    id: Long
    momento: LocalDateTime
    pagamento: FormaPagamento
}

Pagamento "1" --> "1" FormaPagamento
Pedido --> "1" Pagamento

enum FormaPagamento{
    + PIX
    + CREDITO
    + BOLETO 
}

enum StatusPedido{
    + AGUARDANDO_PAGAMENTO
    + PAGAMENTO_REALIZADO
    + ENVIADO
    + ENTREGUE
    + CANCELADO
}

class Peça{
    id: Long
    nome: String
    descricao: String
    preco: Double
    estoque: Integer
    fornecedor: Fornecedor
    categoria: Categoria
}

Peça "*" --> "1" Fornecedor
Peça "*" --> "1" Categoria

enum Categoria{
    + MECANICA
    + SUSPENSAO
    + DIRECAO
    + ESTETICA
    + ELETRICA
}

class Usuario{
    id: Long
    email: String 
    senha: String
    endereco: Endereco
}

Usuario "*" --> "1" Endereco

class Endereco{
    id: Long
    cidade: String
    cep: String
    rua: String
    numero: String
}

enum Perfil{
    + USER
    + ADMIN
}

class Fornecedor{
    id: Long
    nome: String
    cnpj: String
    email: String
    localizacao: Localizacao
}

class Localizacao{
    id: Long
    cidade: String 
    estado: String
}

Fornecedor "1" o--> "*" Localizacao



Usuario "*" --> "1" Perfil

ItemPedido  "*" --> "1"  Peça
Pedido "1" *--> "*" ItemPedido
Pedido "*" --> "1" Usuario

@enduml